apiVersion: v1
kind: Service
metadata:
  name: openwebui-service
spec:
  selector:
    app: openwebui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
  type: LoadBalancer # Or NodePort, depending on your cluster setup
